version: '3.7'

services:
  taskanline_clinet:
    build: .
    container_name: taskanline_client
    ports:
      - '8080:80'
    restart: always
    networks:
      - taskanline-client-network

networks:
  taskanline-client-network:
    external: true
