server {
    listen 80;
    server_name localhost task.tarbieshi.kz;

    # Корень, откуда раздаем статику (совпадает с путем в Dockerfile)
    root /usr/share/nginx/html;
    index index.html;

    # 1. Gzip компрессия (Must-have для продакшена)
    gzip on;
    gzip_min_length 1000;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

    # 2. Обработка роутинга Angular (SPA)
    location / {
        # Пытаемся найти файл -> папку -> иначе отдаем index.html (чтобы Angular Router подхватил url)
        try_files $uri $uri/ /index.html;
    }

    location /api/v1/ {
        proxy_pass http://taskanline_server:8000/api/v1/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 3. Кэширование статики (JS/CSS с хэшами в именах можно кэшировать навечно)
    location ~* \.(?:css|js)$ {
        expires 1y;
        access_log off;
        add_header Cache-Control "public";
    }

    # 4. Кэширование ассетов (картинки, шрифты)
    location ~* \.(?:ico|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 1M;
        access_log off;
        add_header Cache-Control "public";
    }

    # Обработка 404, если нужно (опционально)
    # error_page 404 /index.html;
}
